
language: node_js
node_js:
  - "6"

script:
  - echo "build the application"
  - npm run lint
  - npm run build

after_success:
  - echo "deploy the application"
  - npm run firebase -- deploy --token $FIREBASE_TOKEN
